### PR TITLE
Enable tests for Scala 2.13

### PR DESCRIPTION
**Pull request by fthomas**

### CODE REVIEW

**Comment by fthomas** [comment]
Uh-oh, the tests fail to compile with 2.13:
```
[error] 1752 errors found
[error] 1752 errors found
[error] (singleton_opsJS/test:compileIncremental) Compilation failed
[error] (singleton_opsJVM/test:compileIncremental) Compilation failed
```

**Comment by soronpo** [comment]
Yes, it looks like Scala 2.13.0-M4 has regressions (yet again) for singleton-ops. The regressions seem to only affect the `twoface` part of the library.

**Comment by soronpo** [comment]
Opened an issue. https://github.com/fthomas/singleton-ops/issues/71
The scalac 2.13.x branch has regressions. We need to wait before using it.

**Comment by soronpo** [comment]
The issue will be resolved for 2.13.0-M5
https://github.com/scala/scala/pull/6927

**Comment by soronpo** [comment]
Issues fixed and we're already at 2.13.0-M5
